///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class PGMessage {


  int? mid;
  int? fromId;
  int? toId;
  String? content;
  String? url;
  String? messageType;
  int? timestamp;
  bool? isGroup;

  PGMessage({
    this.mid,
    this.fromId,
    this.toId,
    this.content,
    this.url,
    this.messageType,
    this.timestamp,
    this.isGroup
  });
  PGMessage.fromJson(Map<String, dynamic> json) {
    mid = json["mid"]?.toInt();
    fromId = json["fromId"]?.toInt();
    toId = json["toId"]?.toInt();
    content = json["content"]?.toString();
    url = json["url"]?.toString();
    messageType = json["messageType"]?.toString();
    timestamp = json["timestamp"]?.toInt();
    isGroup = json["isGroup"];
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["mid"] = mid;
    data["fromAccount"] = fromId;
    data["toAccount"] = toId;
    data["content"] = content;
    data["timestamp"] = timestamp;
    return data;
  }
}

